apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ephemeral-test
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/adamyodinsky/argo_tests.git
              revision: HEAD
              files:
                - path: "ephemeral/**/config.yaml"
          - list:
              elements: []
              elementsYaml: "{{ .services | toJson }}"
  template:
    metadata:
      name: "{{.name}}"
    spec:
      project: "{{.name}}"
      source:
        repoURL: https://github.com/adamyodinsky/argo_tests.git
        targetRevision: HEAD
        path: charts/hello-world-b
        helm:
          releaseName: "{{.name}}"
          values: "{{ .values }}"
          # TODO: Add support for valuesObject if possible
          #          valuesObject: {{ .valuesObject }}
          # TODO: Add support for valueFiles
          # Interpolate service name from the config file to the path of the values file
          valueFiles:
            - "values.yaml"
      destination:
        server: https://kubernetes.default.svc
        namespace: "default"
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true
