apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ephemeral-test-1
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
      generators:
        - git:
            repoURL: https://github.com/adamyodinsky/argo_tests.git
            revision: HEAD
            files:
              - path: "ephemeral/a/config.yaml"
        - list:
            elementsYaml: "{{ .key.components | toJson }}"
  template:
    metadata:
      name: "{{.name}}"
    spec:
      project: default
      source:
        chart: hello-world
        repoURL: https://github.com/adamyodinsky/argo_tests.git
        targetRevision: HEAD
        path: /charts/hello-world-a
        helm:
          releaseName: hello-world
          # valueFiles:
          #   - values.yaml
      destination:
        server: "https://kubernetes.default.svc"
        namespace: default
