apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ephemeral-test
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/adamyodinsky/argo_tests.git
              revision: HEAD
              files:
                - path: "ephemeral/**/config.yaml"
          - list:
              elements: []
              elementsYaml: "{{ .services | toJson }}"
  template:
    metadata:
      name: "{{.name}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/helm/charts.git
        targetRevision: HEAD
        path: charts/hello-world
        helm:
          releaseName: "{{.name}}"
          valuesObject: { { .valuesObject | toYaml | nindent 12 } }
        # valueFiles:
        #   - values.yaml
      destination:
        server: "https://kubernetes.default.svc"
        namespace: default
