apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/adamyodinsky/alfa_test.git
        revision: HEAD
        files:
          - path: "ephemeral/**/config.yaml"
  template:
    metadata:
      name: "{{.services.name}}"
    spec:
      project: default
      source:
        chart: hello-world
        repoURL: https://github.com/adamyodinsky/alfa_test.git/charts/hello_world_a
        targetRevision: 1.16.0
        helm:
          releaseName: hello-world
      destination:
        server: "https://kubernetes.default.svc"
        namespace: default
