apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ephemeral-test
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/adamyodinsky/alfa_test.git
        revision: HEAD
        files:
          - path: "ephemeral/a/config.yaml"
  template:
    metadata:
      name: "{{.services.name}}"
    spec:
      project: default
      source:
        chart: hello-world
        repoURL: https://github.com/adamyodinsky/argo_tests
        targetRevision: HEAD
        path: charts/hello-world-a
        helm:
          releaseName: hello-world-1
          # valueFiles:
          #   - values.yaml
      destination:
        server: "https://kubernetes.default.svc"
        namespace: default
