# Iterate via a file with paths to the applicationset files
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gitopsdemo
  namespace: argocd
spec:
  generators:
    # matrix 'parent' generator
    - matrix:
        generators:
          # git generator, 'child' #1
          - git:
              repoURL: https://github.com/adamyodinsky/ephemeralenvironments.git
              revision: HEAD
              files:
                - path: "alfa_test"
          # cluster generator, 'child' #2
          - clusters:
              selector:
                matchLabels:
                  argocd.argoproj.io/secret-type: cluster
                  kubernetes.io/environment: "{{.path.basename}}"
  template:
    metadata:
      name: "{{path.basename}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/adamyodinsky/ephemeralenvironments.git
        targetRevision: HEAD
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        # namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true
