services:
  - name: hello-world-c
    valuesObject:
      valuesObject:
        nameOverride: hello-world-c
        fullnameOverride: hello-world-c
  - name: hello-world-d
    valuesObject:
      valuesObject:
        nameOverride: hello-world-d
        fullnameOverride: hello-world-d
