services:
  - name: tel-aviv
    # values: |
    #   override_name: haifa
    valuesObject:
      replicas: 2
      override_name: haifa

  # - name: talmond
  #   values: |
  #     override_name: talmond-baaaa
  #   valuesObject:
  #     replicas: 2
