services:
  - name: hello-world-c
    valuesObject:
      service:
        type: ClusterIP
        port: 9090
      serviceAccount:
        create: false
  - name: hello-world-d
    valuesObject:
      service:
        type: ClusterIP
        port: 8080
      serviceAccount:
        create: false
