services:
  - name: hello-world-a
    valuesObject: |
      name: hello-world-a
  # - name: hello-world-b
  #   valuesObject:
  #     nameOverride: hello-world-b
  #     fullnameOverride: hello-world-b
