key:
  elements:
    - name: hello-world-a
      # valuesObject:
      #   service:
      #     type: ClusterIP
      #     port: 9000
    - name: hello-world-b
      # valuesObject:
      #   service:
      #     type: ClusterIP
      #     port: 8000
