services:
  - name: hello-world-a
    valuesObject:
      service:
        type: ClusterIP
        port: 9000
      serviceAccount:
        create: false
  - name: hello-world-b
    valuesObject:
      service:
        type: ClusterIP
        port: 8000
      serviceAccount:
        create: false
