apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.override_name }}"
spec:
  selector:
    app.kubernetes.io/name: "{{ .Values.override_name }}"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
